# Generated by Django 3.1.7 on 2021-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('source', 'Source'), ('seed', 'Seed'), ('commercial', 'Commercial'), ('foundation_farm', 'Foundation Farm')], default='seed', max_length=30)),
                ('crop', models.CharField(choices=[('soybeans', 'Soybeans'), ('groundnuts', 'Groundnuts'), ('beans', 'Beans'), ('cowpeas', 'Cowpeas'), ('pigeon_pea', 'Pigeon-Pea'), ('green_gram', 'Green-Gram')], default='soybeans', max_length=30)),
                ('variety', models.CharField(choices=[('kafue', 'Kafue'), ('tgx', 'TGX'), ('mgv4', 'MGV4'), ('mgv5', 'MGV5'), ('mgv7', 'MGV7'), ('mgv8', 'MGV8'), ('wamusanga', 'Wamusanga'), ('lupande', 'Lupande'), ('aqua', 'Aqua'), ('chishango', 'Chishango'), ('lutembwe', 'Lutembwe'), ('bubebe', 'Bubebe'), ('black_eyed', 'Black-Eyed'), ('msandile', 'Msandile'), ('madagascar', 'Madagascar'), ('kabulangeti', 'Kabulangeti'), ('luangeni', 'Luangeni'), ('bounty', 'Bounty'), ('kalungu', 'Kalungu'), ('mbereshi', 'Mbereshi'), ('lungwe_bungu', 'Lungwe-Bungu'), ('mthawa_june', 'Mthawa-June'), ('sheni', 'Sheni')], default='kafue', max_length=30)),
                ('season', models.CharField(choices=[('2019_2020', '2019-2020'), ('2020_2021', '2020-2021')], default='2020_2021', max_length=30)),
                ('camp', models.CharField(blank=True, max_length=50)),
                ('field_supervisor', models.CharField(blank=True, max_length=100)),
                ('purchased_weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processed_weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cleaned_weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sorts_weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waste_weight_mt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchased_amount_zmw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
