# Generated by Django 3.1.7 on 2021-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingdata',
            name='purchased_amount_zmw',
        ),
    ]
