# Generated by Django 3.1.7 on 2021-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuybackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('crop', models.CharField(max_length=30)),
                ('variety', models.CharField(max_length=30)),
                ('season', models.CharField(max_length=30)),
                ('camp', models.CharField(max_length=30)),
                ('total_yield_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_yield_bought_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_purchased_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
