# Generated by Django 3.1.7 on 2021-03-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0002_auto_20210325_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybackdata',
            name='field_supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='buybackdata',
            name='camp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
