# Generated by Django 3.1.7 on 2021-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0003_auto_20210325_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybackdata',
            name='actual_yields_weight_mt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buybackdata',
            name='category',
            field=models.CharField(choices=[('source', 'Source'), ('seed', 'Seed'), ('commercial', 'Commercial'), ('foundation_farm', 'Foundation Farm')], default='seed', max_length=30),
        ),
        migrations.AlterField(
            model_name='buybackdata',
            name='total_purchased_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buybackdata',
            name='yields_estimates_weight_mt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
