# Generated by Django 3.1.7 on 2021-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0004_auto_20210402_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybackdata',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
