# Generated by Django 3.1.7 on 2021-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0005_buybackdata_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybackdata',
            name='crop',
            field=models.CharField(choices=[('soybeans', 'Soybeans'), ('groundnuts', 'Groundnuts'), ('beans', 'Beans'), ('cowpeas', 'Cowpeas')], default='soybeans', max_length=30),
        ),
    ]
