# Generated by Django 3.1.7 on 2021-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0006_auto_20210402_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybackdata',
            name='crop',
            field=models.CharField(choices=[('soybeans', 'Soybeans'), ('groundnuts', 'Groundnuts'), ('beans', 'Beans'), ('cowpeas', 'Cowpeas'), ('pigeon_pea', 'Pigeon-Pea'), ('green_gram', 'Green-Gram')], default='soybeans', max_length=30),
        ),
        migrations.AlterField(
            model_name='buybackdata',
            name='variety',
            field=models.CharField(choices=[('kafue', 'Kafue'), ('tgx', 'TGX'), ('mgv4', 'MGV4'), ('mgv5', 'MGV5'), ('mgv7', 'MGV7'), ('mgv8', 'MGV8'), ('wamusanga', 'Wamusanga'), ('lupande', 'Lupande'), ('aqua', 'Aqua'), ('chishango', 'Chishango'), ('lutembwe', 'Lutembwe'), ('bubebe', 'Bubebe'), ('black_eyed', 'Black-Eyed'), ('msandile', 'Msandile'), ('madagascar', 'Madagascar'), ('kabulangeti', 'Kabulangeti'), ('luangeni', 'Luangeni'), ('bounty', 'Bounty'), ('kalungu', 'Kalungu'), ('mbereshi', 'Mbereshi'), ('lungwe_bungu', 'Lungwe-Bungu'), ('mthawa_june', 'Mthawa-June'), ('sheni', 'Sheni')], default='kafue', max_length=30),
        ),
    ]
