# Generated by Django 3.1.7 on 2021-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0007_auto_20210501_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buybackdata',
            old_name='total_purchased_amount',
            new_name='total_purchased_amount_zmw',
        ),
        migrations.AddField(
            model_name='buybackdata',
            name='total_farmers_purchased_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buybackdata',
            name='total_hectares_purchased_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buybackdata',
            name='total_purchased_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
