# Generated by Django 3.1.7 on 2021-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0009_buybackdata_total_farmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybackdata',
            name='paid_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buybackdata',
            name='paid_amount_zmw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
