# Generated by Django 3.1.7 on 2023-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyback_data', '0013_auto_20230619_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybackdata',
            name='category',
            field=models.CharField(choices=[('source', 'Source'), ('seed', 'Seed'), ('commercial', 'Commercial'), ('malawi', 'Malawi'), ('foundation_farm', 'Foundation Farm')], default='seed', max_length=30),
        ),
    ]
